using System.Collections.Generic;
using System.Linq;
using CreativeCode.JWK.KeyParts;
using FluentAssertions;
using Newtonsoft.Json.Linq;
using Xunit;
using static CreativeCode.JWK.Base64Helper;

namespace CreativeCode.JWK.Tests
{
    public class JWKValidationTests
    {
        private static JObject ExportedKey(Algorithm algorithm)
        {
            var jwk = new JWK(algorithm, PublicKeyUse.Signature, new[] { KeyOperation.ComputeDigitalSignature });
            return JObject.Parse(jwk.Export(KeyMembers.All));
        }

        #region Valid keys

        [Fact]
        public void JWKWithRSAKeyCanBeParsed()
        {
            var success = JWK.TryParse(ExportedKey(Algorithm.RS256).ToString(), out var jwk, out var errors);

            errors.Should().BeEmpty();
            success.Should().BeTrue();
            jwk.KeyType.Should().Be(KeyType.RSA);
        }

        [Theory]
        [InlineData("ES256", "P-256")]
        [InlineData("ES384", "P-384")]
        [InlineData("ES512", "P-521")]
        public void JWKWithECKeyUsesCurveOfItsAlgorithm(string algorithmName, string expectedCurve)
        {
            var exported = ExportedKey(Algorithm.TryGetAlgorithm(algorithmName));
            exported.GetValue("crv").ToString().Should().Be(expectedCurve, "RFC 7518 - Section 3.4 defines the curve of an ECDSA algorithm");

            var success = JWK.TryParse(exported.ToString(), out var jwk, out var errors);

            errors.Should().BeEmpty("a key generated by this library is a point on the curve it claims");
            success.Should().BeTrue();
            jwk.GetCurve().Name.Should().Be(expectedCurve);
        }

        [Fact]
        public void JWKWithPublicKeyOnlyCanBeParsed()
        {
            var jwk = new JWK(Algorithm.RS256, PublicKeyUse.Signature, new[] { KeyOperation.VerifyDigitalSignature });

            JWK.TryParse(jwk.Export(KeyMembers.Public), out _, out var errors).Should().BeTrue();
            errors.Should().BeEmpty();
        }

        [Fact]
        public void JWKWithLegacyCurveNameCanBeParsed()
        {
            var exported = ExportedKey(Algorithm.ES512);
            exported["crv"] = "P-512"; // The name this library used up to and including 0.7.1

            JWK.TryParse(exported.ToString(), out var jwk, out var errors).Should().BeTrue();
            errors.Should().BeEmpty();
            jwk.GetCurve().Should().Be(EllipticCurve.P521);
        }

        #endregion Valid keys

        #region Structural errors

        [Fact]
        public void JWKWithoutKeyTypeCannotBeParsed()
        {
            var exported = ExportedKey(Algorithm.RS256);
            exported.Remove("kty");

            JWK.TryParse(exported.ToString(), out var jwk, out var errors).Should().BeFalse();
            jwk.Should().BeNull();
            errors.Should().ContainSingle().Which.Should().Contain("'kty'");
        }

        [Fact]
        public void JWKWithUnknownKeyTypeCannotBeParsed()
        {
            var exported = ExportedKey(Algorithm.RS256);
            exported["kty"] = "OKP";

            JWK.TryParse(exported.ToString(), out _, out var errors).Should().BeFalse();
            errors.Should().ContainSingle().Which.Should().Contain("'OKP' is not supported");
        }

        [Fact]
        public void JWKWithNonStringAlgorithmCannotBeParsed()
        {
            var exported = ExportedKey(Algorithm.RS256);
            exported["alg"] = 256;

            JWK.TryParse(exported.ToString(), out _, out var errors).Should().BeFalse();
            errors.Should().ContainSingle().Which.Should().Contain("('alg') MUST be a JSON string");
        }

        [Fact]
        public void JWKWithNonStringKeyParameterCannotBeParsed()
        {
            var exported = ExportedKey(Algorithm.RS256);
            exported["e"] = 65537;

            JWK.TryParse(exported.ToString(), out _, out var errors).Should().BeFalse();
            errors.Should().ContainSingle().Which.Should().Contain("'e' MUST be a JSON string");
        }

        [Fact]
        public void JWKWithNonStringPublicKeyUseCannotBeParsed()
        {
            var exported = ExportedKey(Algorithm.RS256);
            exported["use"] = 1;

            JWK.TryParse(exported.ToString(), out _, out var errors).Should().BeFalse();
            errors.Should().ContainSingle().Which.Should().Contain("('use') MUST be a JSON string");
        }

        [Fact]
        public void JWKWithNonArrayKeyOperationsCannotBeParsed()
        {
            var exported = ExportedKey(Algorithm.RS256);
            exported["key_ops"] = "sign"; // A single string instead of an array, which would silently be read as no operations at all

            JWK.TryParse(exported.ToString(), out _, out var errors).Should().BeFalse();
            errors.Should().ContainSingle().Which.Should().Contain("('key_ops') MUST be a JSON array");
        }

        [Fact]
        public void JWKWithNonStringKeyOperationCannotBeParsed()
        {
            var exported = ExportedKey(Algorithm.RS256);
            exported["key_ops"] = new JArray(new JObject { ["a"] = 1 });

            JWK.TryParse(exported.ToString(), out _, out var errors).Should().BeFalse();
            errors.Should().ContainSingle().Which.Should().Contain("('key_ops') MUST be a JSON string");
        }

        [Fact]
        public void JWKWithMultipleErrorsReportsAllOfThem()
        {
            var exported = ExportedKey(Algorithm.RS256);
            exported.Remove("n");
            exported["e"] = "not base64url!";

            JWK.TryParse(exported.ToString(), out _, out var errors).Should().BeFalse();
            errors.Should().HaveCount(2);
        }

        #endregion Structural errors

        #region Key material errors

        [Fact]
        public void JWKWithoutMandatoryKeyParameterCannotBeParsed()
        {
            var exported = ExportedKey(Algorithm.RS256);
            exported.Remove("n");

            JWK.TryParse(exported.ToString(), out _, out var errors).Should().BeFalse();
            errors.Should().ContainSingle().Which.Should().Contain("'n' is missing");
        }

        [Fact]
        public void JWKWithInvalidBase64urlCannotBeParsed()
        {
            var exported = ExportedKey(Algorithm.RS256);
            exported["n"] = "this+is/standard+base64==";

            JWK.TryParse(exported.ToString(), out _, out var errors).Should().BeFalse();
            errors.Should().ContainSingle().Which.Should().Contain("'n' is not a valid base64url encoded value");
        }

        [Fact]
        public void JWKWithLeadingZeroOctetCannotBeParsed()
        {
            var exported = ExportedKey(Algorithm.RS256);
            var modulus = Base64urlDecode(exported.GetValue("n").ToString());
            exported["n"] = Base64urlEncode(new byte[] { 0x00 }.Concat(modulus).ToArray());

            JWK.TryParse(exported.ToString(), out _, out var errors).Should().BeFalse();
            errors.Should().ContainSingle().Which.Should().Contain("leading zero octet");
        }

        [Fact]
        public void JWKWithUnknownCurveCannotBeParsed()
        {
            var exported = ExportedKey(Algorithm.ES256);
            exported["crv"] = "P-192";

            JWK.TryParse(exported.ToString(), out _, out var errors).Should().BeFalse();
            errors.Should().ContainSingle().Which.Should().Contain("'P-192' is not supported");
        }

        [Fact]
        public void JWKWithUnpaddedCoordinateCannotBeParsed()
        {
            var exported = ExportedKey(Algorithm.ES256);
            var x = Base64urlDecode(exported.GetValue("x").ToString());
            exported["x"] = Base64urlEncode(x.Skip(1).ToArray()); // 31 instead of 32 octets

            JWK.TryParse(exported.ToString(), out _, out var errors).Should().BeFalse();
            errors.Should().Contain(error => error.Contains("'x' is 31 octets long"));
        }

        [Fact]
        public void JWKWithPointNotOnCurveCannotBeParsed()
        {
            var exported = ExportedKey(Algorithm.ES256);
            var x = Base64urlDecode(exported.GetValue("x").ToString());
            x[x.Length - 1] ^= 0x01; // Corrupt the point, but keep the length
            exported["x"] = Base64urlEncode(x);

            JWK.TryParse(exported.ToString(), out _, out var errors).Should().BeFalse();
            errors.Should().ContainSingle().Which.Should().Contain("is not a point on curve 'P-256'");
        }

        [Fact]
        public void JWKWithIncompletePrivateRSAKeyCannotBeParsed()
        {
            // See RFC 7518 - Section 6.3.2: if any of the other private key parameters is present, all MUST be present
            var exported = ExportedKey(Algorithm.RS256);
            exported.Remove("q");
            exported.Remove("dq");

            JWK.TryParse(exported.ToString(), out _, out var errors).Should().BeFalse();
            errors.Should().ContainSingle().Which.Should().Contain("'q'").And.Contain("'dq'");
        }

        [Fact]
        public void JWKCanBeValidated()
        {
            var keyParameters = new Dictionary<KeyParameter, string>
            {
                {KeyParameter.RSAKeyParameterN, "not a modulus"}, // Not base64url encoded key material
                {KeyParameter.RSAKeyParameterE, "AQAB"}
            };
            var jwk = new JWK(KeyType.RSA, keyParameters);

            jwk.TryValidate(out var errors).Should().BeFalse();
            errors.Should().ContainSingle().Which.Should().Contain("'n'");
        }

        #endregion Key material errors

        #region Key sets

        [Fact]
        public void JWKSWithMultipleMixedKeysCanBeParsed()
        {
            var jwks = new JWKS(new[]
            {
                new JWK(Algorithm.RS256, PublicKeyUse.Signature, new[] { KeyOperation.VerifyDigitalSignature }),
                new JWK(Algorithm.ES384, PublicKeyUse.Signature, new[] { KeyOperation.VerifyDigitalSignature })
            });

            JWKS.TryParse(jwks.Export(KeyMembers.Public), out var parsed, out var errors).Should().BeTrue();
            errors.Should().BeEmpty();
            parsed.Keys.Should().HaveCount(2);
        }

        [Fact]
        public void JWKSWithDuplicateKeyIdCannotBeParsed()
        {
            var first = JObject.Parse(new JWK(Algorithm.RS256, PublicKeyUse.Signature, new[] { KeyOperation.VerifyDigitalSignature }).Export(KeyMembers.Public));
            var second = JObject.Parse(new JWK(Algorithm.ES256, PublicKeyUse.Signature, new[] { KeyOperation.VerifyDigitalSignature }).Export(KeyMembers.Public));
            second["kid"] = first.GetValue("kid").ToString();
            var jwks = new JObject { ["keys"] = new JArray(first, second) };

            JWKS.TryParse(jwks.ToString(), out _, out var errors).Should().BeFalse();
            errors.Should().ContainSingle().Which.Should().Contain("used by more than one key");
        }

        [Fact]
        public void JWKSReportsPositionOfFailingKey()
        {
            var first = JObject.Parse(new JWK(Algorithm.RS256, PublicKeyUse.Signature, new[] { KeyOperation.VerifyDigitalSignature }).Export(KeyMembers.Public));
            var second = JObject.Parse(new JWK(Algorithm.ES256, PublicKeyUse.Signature, new[] { KeyOperation.VerifyDigitalSignature }).Export(KeyMembers.Public));
            second.Remove("x");
            var jwks = new JObject { ["keys"] = new JArray(first, second) };

            JWKS.TryParse(jwks.ToString(), out _, out var errors).Should().BeFalse();
            errors.Should().ContainSingle().Which.Should().StartWith("Key at position 1:");
        }

        [Fact]
        public void JWKSWithEmptyKeysCannotBeParsed()
        {
            JWKS.TryParse("{\"keys\":[]}", out var jwks, out var errors).Should().BeFalse();
            jwks.Should().BeNull();
            errors.Should().ContainSingle().Which.Should().Contain("'keys' array is empty");
        }

        [Fact]
        public void JWKSWithoutKeysCannotBeParsed()
        {
            JWKS.TryParse("{}", out _, out var errors).Should().BeFalse();
            errors.Should().ContainSingle().Which.Should().Contain("'keys' member is missing");
        }

        [Fact]
        public void JWKSWithInvalidJSONCannotBeParsed()
        {
            JWKS.TryParse("not json", out _, out var errors).Should().BeFalse();
            errors.Should().ContainSingle().Which.Should().Contain("not a valid JSON object");
        }

        #endregion Key sets
    }
}
